/**
 * All 25 administrative districts of Sri Lanka with every major town /
 * divisional-secretariat town in each, updated September 2026.
 *
 * Used in the quote form so the town dropdown is filtered to only show
 * towns that belong to the selected district.
 */
export const sriLankaDistrictTowns: Record<string, string[]> = {
  // ── Western Province ────────────────────────────────────────────────────
  Colombo: [
    "Colombo 01 (Fort)",
    "Colombo 02 (Slave Island)",
    "Colombo 03 (Kollupitiya)",
    "Colombo 04 (Bambalapitiya)",
    "Colombo 05 (Havelock Town)",
    "Colombo 06 (Wellawatta)",
    "Colombo 07 (Cinnamon Gardens)",
    "Colombo 08 (Borella)",
    "Colombo 09 (Dematagoda)",
    "Colombo 10 (Maradana)",
    "Colombo 11 (Pettah)",
    "Colombo 12 (Hulftsdorp)",
    "Colombo 13 (Kotahena)",
    "Colombo 14 (Grandpass)",
    "Colombo 15 (Mattakkuliya)",
    "Dehiwala",
    "Mount Lavinia",
    "Moratuwa",
    "Kesbewa",
    "Sri Jayawardenepura Kotte",
    "Nugegoda",
    "Maharagama",
    "Boralesgamuwa",
    "Piliyandala",
    "Kaduwela",
    "Kolonnawa",
    "Hanwella",
    "Padukka",
    "Homagama",
    "Avissawella",
    "Seethawaka",
  ],
  Gampaha: [
    "Gampaha",
    "Negombo",
    "Ja-Ela",
    "Wattala",
    "Kelaniya",
    "Peliyagoda",
    "Ragama",
    "Mahara",
    "Kadawatha",
    "Kiribathgoda",
    "Veyangoda",
    "Mirigama",
    "Divulapitiya",
    "Nittambuwa",
    "Biyagama",
    "Minuwangoda",
    "Katana",
    "Seeduwa",
    "Attanagalla",
    "Dompe",
  ],
  Kalutara: [
    "Kalutara",
    "Panadura",
    "Horana",
    "Beruwala",
    "Bandaragama",
    "Mathugama",
    "Agalawatta",
    "Madurawela",
    "Ingiriya",
    "Dodangoda",
    "Millaniya",
    "Bulathsinhala",
    "Walallawita",
    "Palindanuwara",
    "Bentota",
    "Aluthgama",
    "Balapitiya",
    "Wadduwa",
  ],

  // ── Central Province ─────────────────────────────────────────────────────
  Kandy: [
    "Kandy",
    "Peradeniya",
    "Katugastota",
    "Gampola",
    "Nawalapitiya",
    "Akurana",
    "Kundasale",
    "Digana",
    "Pilimatalawa",
    "Gelioya",
    "Harispattuwa",
    "Udunuwara",
    "Yatinuwara",
    "Poojapitiya",
    "Delthota",
    "Teldeniya",
    "Medadumbara",
    "Pathadumbara",
    "Hatharaliyadda",
    "Wattegama",
    "Minipe",
    "Pasbage Korale",
    "Tumpane",
  ],
  Matale: [
    "Matale",
    "Dambulla",
    "Sigiriya",
    "Naula",
    "Galewela",
    "Ukuwela",
    "Rattota",
    "Yatawatta",
    "Wilgamuwa",
    "Pallepola",
    "Ambanganga Korale",
    "Laggala-Pallegama",
  ],
  "Nuwara Eliya": [
    "Nuwara Eliya",
    "Hatton",
    "Kotagala",
    "Thalawakele",
    "Lindula",
    "Bogawantalawa",
    "Norwood",
    "Ambewela",
    "Ragala",
    "Walapane",
    "Kotmale",
    "Hanguranketha",
    "Udapalatha",
  ],

  // ── Southern Province ────────────────────────────────────────────────────
  Galle: [
    "Galle",
    "Hikkaduwa",
    "Unawatuna",
    "Ahangama",
    "Ambalangoda",
    "Balapitiya",
    "Elpitiya",
    "Baddegama",
    "Neluwa",
    "Nagoda",
    "Imaduwa",
    "Karandeniya",
    "Yakkalamulla",
    "Niyagama",
    "Habaraduwa",
    "Welivitiya-Divithura",
    "Thawalama",
    "Gonapinuwala",
    "Akmeemana",
    "Bentara-Elpitiya",
  ],
  Matara: [
    "Matara",
    "Weligama",
    "Mirissa",
    "Dickwella",
    "Akuressa",
    "Kamburupitiya",
    "Devinuwara",
    "Hakmana",
    "Malimbada",
    "Kotapola",
    "Welipitiya",
    "Athuraliya",
    "Pasgoda",
    "Kirinda Puhulwella",
    "Pitabeddara",
    "Mulatiyana",
    "Weligama",
    "Deniyaya",
  ],
  Hambantota: [
    "Hambantota",
    "Tangalle",
    "Tissamaharama",
    "Weeraketiya",
    "Ambalantota",
    "Beliatta",
    "Walasmulla",
    "Katuwana",
    "Lunugamvehera",
    "Okewela",
    "Sooriyawewa",
    "Angunakolapelessa",
    "Mulkirigala",
  ],

  // ── Northern Province ────────────────────────────────────────────────────
  Jaffna: [
    "Jaffna",
    "Nallur",
    "Chavakachcheri",
    "Point Pedro",
    "Manipay",
    "Kayts",
    "Karainagar",
    "Sandilipay",
    "Uduvil",
    "Tellippalai",
    "Chunnakam",
    "Kopay",
    "Valvettithurai",
    "Delft",
    "Neduntivu",
    "Island North",
    "Island South",
  ],
  Kilinochchi: [
    "Kilinochchi",
    "Kandawalai",
    "Karachchi",
    "Pachchilaipalli",
    "Poonakary",
  ],
  Mannar: [
    "Mannar",
    "Nanatan",
    "Manthai West",
    "Musalai",
    "Madhu",
  ],
  Vavuniya: [
    "Vavuniya",
    "Vavuniya North",
    "Vavuniya South",
    "Vengalacheddikulam",
  ],
  Mullaitivu: [
    "Mullaitivu",
    "Manthai East",
    "Maritimepattu",
    "Oddusuddan",
    "Puthukudiyiruppu",
    "Thunukkai",
    "Welioya",
  ],

  // ── Eastern Province ─────────────────────────────────────────────────────
  Batticaloa: [
    "Batticaloa",
    "Kattankudy",
    "Valaichenai",
    "Paddippalai",
    "Manmunai North",
    "Manmunai South & Eruvil Pattu",
    "Manmunai West",
    "Manmunai Pattu",
    "Koralai Pattu",
    "Koralai Pattu North",
    "Koralai Pattu West",
    "Porativu Pattu",
    "Eravur Pattu",
    "Eravur Town",
  ],
  Ampara: [
    "Ampara",
    "Kalmunai",
    "Sainthamaruthu",
    "Sammanthurai",
    "Pottuvil",
    "Arugam Bay",
    "Akkaraipattu",
    "Dehiattakandiya",
    "Maha Oya",
    "Uhana",
    "Mahaoya",
    "Damana",
    "Irakkamam",
    "Addalaichenai",
    "Thirukkovil",
    "Padiyathalawa",
    "Lahugala",
  ],
  Trincomalee: [
    "Trincomalee",
    "Kinniya",
    "Mutur",
    "Kantale",
    "Seruwila",
    "Thampalakamam",
    "Morawewa",
    "Gomarankadawala",
    "Kuchchaveli",
    "Verugal",
  ],

  // ── North-Western Province ────────────────────────────────────────────────
  Kurunegala: [
    "Kurunegala",
    "Kuliyapitiya",
    "Polgahawela",
    "Mawathagama",
    "Nikaweratiya",
    "Wariyapola",
    "Pannala",
    "Ibbagamuwa",
    "Galewela",
    "Galgamuwa",
    "Giribawa",
    "Alawwa",
    "Bingiriya",
    "Kotavehera",
    "Maspotha",
    "Narammala",
    "Polpithigama",
    "Rideegama",
    "Ambanpola",
    "Bamunakotuwa",
    "Dodangaslanda",
    "Ehetuwewa",
    "Ganewatta",
    "Mahawa",
    "Mallawapitiya",
    "Meerigama",
    "Divulapitiya",
  ],
  Puttalam: [
    "Puttalam",
    "Chilaw",
    "Wennappuwa",
    "Nattandiya",
    "Madurankuliya",
    "Anamaduwa",
    "Mahawewa",
    "Pallama",
    "Dankotuwa",
    "Mundel",
    "Nawagattegama",
    "Kalpitiya",
    "Karuwalagaswewa",
    "Arachchikattuwa",
    "Vanathavilluwa",
  ],

  // ── North-Central Province ────────────────────────────────────────────────
  Anuradhapura: [
    "Anuradhapura",
    "Kekirawa",
    "Medawachchiya",
    "Mihintale",
    "Nochchiyagama",
    "Padaviya",
    "Kahatagasdigiliya",
    "Rajanganaya",
    "Thirappane",
    "Galenbindunuwewa",
    "Thalawa",
    "Nuwaragam Palatha East",
    "Nuwaragam Palatha Central",
    "Nachchadoowa",
    "Ipalogama",
    "Galnewa",
    "Kebithigollewa",
    "Horowpothana",
    "Thambuttegama",
  ],
  Polonnaruwa: [
    "Polonnaruwa",
    "Hingurakgoda",
    "Medirigiriya",
    "Lankapura",
    "Dimbulagala",
    "Welikanda",
    "Thamankaduwa",
    "Elahera",
    "Manampitiya",
  ],

  // ── Uva Province ─────────────────────────────────────────────────────────
  Badulla: [
    "Badulla",
    "Bandarawela",
    "Ella",
    "Haputale",
    "Welimada",
    "Mahiyangana",
    "Passara",
    "Hali Ela",
    "Diyatalawa",
    "Lunugala",
    "Uva Paranagama",
    "Meegahakivula",
    "Soranathota",
    "Kandaketiya",
    "Ridimaliyadda",
    "Haldummulla",
  ],
  Monaragala: [
    "Monaragala",
    "Bibile",
    "Wellawaya",
    "Medagama",
    "Buttala",
    "Kataragama",
    "Siyambalanduwa",
    "Badalkumbura",
    "Sevanagala",
    "Thanamalvila",
    "Madulla",
  ],

  // ── Sabaragamuwa Province ─────────────────────────────────────────────────
  Ratnapura: [
    "Ratnapura",
    "Balangoda",
    "Embilipitiya",
    "Kahawatta",
    "Elapatha",
    "Kuruvita",
    "Imbulpe",
    "Pelmadulla",
    "Kiriella",
    "Ayagama",
    "Nivithigala",
    "Opanayake",
    "Weligepola",
    "Kolonna",
    "Godakawela",
  ],
  Kegalle: [
    "Kegalle",
    "Mawanella",
    "Rambukkana",
    "Galigedara",
    "Galigamuwa",
    "Ruwanwella",
    "Aranayaka",
    "Yatiyanthota",
    "Bulathkohupitiya",
    "Deraniyagala",
    "Warakapola",
    "Dehiovita",
  ],
};

/** Flat sorted list of all districts — for the district dropdown. */
export const sriLankanDistricts = Object.keys(sriLankaDistrictTowns).sort() as string[];
